### ISSUE TITLE
Auto Map Markers - Crash on trader interaction (solved, close pls)

### ISSUE THREAD

**Issue by DonZekane** [egocarib/Vintage-Story-Mods#7]
Log:

```
Running on 64 bit Windows with 8 GB RAM 
Game Version: v1.18.5 (Stable)
02.06.2023 12:38:39: Critical error occurred in the following mod: egocaribautomapmarkers@2.4.0-pre.1
Loaded Mods: emotemenu@1.0.4, immersivecorpsedrop@1.0.1, moreparchment@1.0.0, nailsmold@1.0.1, game@1.18.5, egocaribautomapmarkers@2.4.0-pre.1, betterfirepit@1.1.0, branchcutter@1.0.1, carryon@1.2.0, farmlanddropssoil@1.4.0, hudclock@3.1.0, lessbears@1.0.0, prospectorinfo@4.3.0, roomindicator@1.1.0, creative@1.18.5, survival@1.18.5, workbenchexpansion@1.6.3
Involved Harmony IDs: Egocarib.AutoMapMarkers.Patches
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.Entities.Entity.Pos'.
   at Egocarib.AutoMapMarkers.EntityBehavior.TraderMarkerBehavior.OnInteract(EntityAgent byEntity, ItemSlot itemslot, Vec3d hitPosition, EnumInteractMode mode, EnumHandling& handled)
   at Egocarib.AutoMapMarkers.Patches.EntityTrader.Base_OnInteract_Patch0(Object instance, EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode)
   at Egocarib.AutoMapMarkers.Patches.EntityTrader.Prefix(EntityTrader __instance, EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode) in C:\Users\justin\source\repos\VintageStory\vsmodtemplate-1.5.5\mods\egocaribautomapmarkers\src\Patches\EntityTrader.cs:line 25
   at Vintagestory.GameContent.EntityTrader.OnInteract_Patch1(EntityTrader this, EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 438
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 197
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 789
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 981
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 243
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 724
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 04.05.2023 12:19:07, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.1.0
P3: 10.0.19045.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Mike\AppData\Local\Temp\RDRCFF7.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD0F2.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD151.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD21A.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD2B8.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: ee948a69-5990-4227-b097-affb0cad6672
Report Status: 536870914
Hashed bucket: 
Cab Guid: 0 }
```

**Comment by DonZekane** [comment]
My bad, I'm a dumbass, I completely forgot about the version for 1.18 in the VS mod db comments, I rush-reinstalled the game and redownloaded all the mods in a hurry.
(User Error, I used the 1.17~ version)

**Comment by egocarib** [comment]
Glad you figured it out!
